// Vendored from snz-design tokens/dist/snz-tokens.ts at 9584b5b (trial of TASK-13 in snz-design).
// Do not edit here; the source of truth is snz-design tokens/tokens.json.

// GENERATED by tokens/build.mjs from tokens/tokens.json. Do not edit; edit tokens.json and rebuild.
//
// Colours are #rrggbb, dimensions and shadows are CSS value strings, durations are numbers in milliseconds.

export type SnzColorFamily = "standard" | "solarized";
export type SnzColorMode = "light" | "dark";

export interface SnzColors {
  readonly canvas: string;
  readonly surface: string;
  readonly surfaceAlt: string;
  readonly surfaceHover: string;
  readonly surfaceSelected: string;
  readonly fg: string;
  readonly fgStrong: string;
  readonly fgMuted: string;
  readonly fgFaint: string;
  readonly lineControl: string;
  readonly lineDivider: string;
  readonly focus: string;
  readonly selected: string;
  readonly accent: string;
  readonly accentHover: string;
  readonly onAccent: string;
  readonly accentSoft: string;
  readonly onAccentSoft: string;
  readonly danger: string;
  readonly onDanger: string;
  readonly dangerSoft: string;
  readonly onDangerSoft: string;
  readonly warn: string;
  readonly warnSoft: string;
  readonly onWarnSoft: string;
  readonly success: string;
  readonly successSoft: string;
  readonly onSuccessSoft: string;
  readonly figure: string;
}

export const snzColors: { readonly [F in SnzColorFamily]: { readonly [M in SnzColorMode]: SnzColors } } = {
  standard: {
    light: {
      canvas: "#f2f4f7",
      surface: "#ffffff",
      surfaceAlt: "#e9ecf1",
      surfaceHover: "#e2e6ed",
      surfaceSelected: "#dde8f7",
      fg: "#232a36",
      fgStrong: "#12171f",
      fgMuted: "#555e6c",
      fgFaint: "#5f6875",
      lineControl: "#767f8c",
      lineDivider: "#d7dbe2",
      focus: "#1155a6",
      selected: "#1155a6",
      accent: "#14549e",
      accentHover: "#0f4480",
      onAccent: "#ffffff",
      accentSoft: "#dbe7f7",
      onAccentSoft: "#0f4478",
      danger: "#b02318",
      onDanger: "#ffffff",
      dangerSoft: "#fbe2df",
      onDangerSoft: "#8a1b13",
      warn: "#855400",
      warnSoft: "#f9eccd",
      onWarnSoft: "#66400a",
      success: "#17632e",
      successSoft: "#dcefe1",
      onSuccessSoft: "#114d24",
      figure: "#555e6c",
    },
    dark: {
      canvas: "#191d24",
      surface: "#232833",
      surfaceAlt: "#171b21",
      surfaceHover: "#2b3140",
      surfaceSelected: "#23344a",
      fg: "#dde3ec",
      fgStrong: "#f3f6fa",
      fgMuted: "#a6b0bd",
      fgFaint: "#9ba5b3",
      lineControl: "#79838f",
      lineDivider: "#343b46",
      focus: "#79b4ee",
      selected: "#79b4ee",
      accent: "#7cb2ec",
      accentHover: "#9cc6f3",
      onAccent: "#0d1a26",
      accentSoft: "#1d3049",
      onAccentSoft: "#a9cdf3",
      danger: "#f28b7d",
      onDanger: "#2c0c07",
      dangerSoft: "#3b1b17",
      onDangerSoft: "#f5aca1",
      warn: "#dda93f",
      warnSoft: "#382c11",
      onWarnSoft: "#e3b866",
      success: "#6bbd7c",
      successSoft: "#16301c",
      onSuccessSoft: "#8ccf99",
      figure: "#a6b0bd",
    },
  },
  solarized: {
    light: {
      canvas: "#eee8d5",
      surface: "#fdf6e3",
      surfaceAlt: "#eee8d5",
      surfaceHover: "#ece6d2",
      surfaceSelected: "#e2e7e2",
      fg: "#073642",
      fgStrong: "#002b36",
      fgMuted: "#4f6569",
      fgFaint: "#55686c",
      lineControl: "#657b83",
      lineDivider: "#ded7c0",
      focus: "#1a6a9e",
      selected: "#1a6a9e",
      accent: "#1a6a9e",
      accentHover: "#145682",
      onAccent: "#fdf6e3",
      accentSoft: "#dce7ea",
      onAccentSoft: "#10516f",
      danger: "#b3211f",
      onDanger: "#fdf6e3",
      dangerSoft: "#f6dfd2",
      onDangerSoft: "#8f1a18",
      warn: "#8a6100",
      warnSoft: "#f3e6c4",
      onWarnSoft: "#6c4c00",
      success: "#4f6000",
      successSoft: "#e6e8cc",
      onSuccessSoft: "#3f4d00",
      figure: "#4f6569",
    },
    dark: {
      canvas: "#002b36",
      surface: "#073642",
      surfaceAlt: "#002b36",
      surfaceHover: "#0a3b47",
      surfaceSelected: "#0b3946",
      fg: "#eee8d5",
      fgStrong: "#fdf6e3",
      fgMuted: "#93a1a1",
      fgFaint: "#909f9f",
      lineControl: "#6f8385",
      lineDivider: "#14424f",
      focus: "#6cb6e8",
      selected: "#6cb6e8",
      accent: "#6cb6e8",
      accentHover: "#8ec9ef",
      onAccent: "#002b36",
      accentSoft: "#123c4c",
      onAccentSoft: "#8fc9ee",
      danger: "#f08b7f",
      onDanger: "#2b0c08",
      dangerSoft: "#3c1b18",
      onDangerSoft: "#f2a99f",
      warn: "#b58900",
      warnSoft: "#33290f",
      onWarnSoft: "#d9b45c",
      success: "#859900",
      successSoft: "#232a10",
      onSuccessSoft: "#a9b95a",
      figure: "#93a1a1",
    },
  },
};

export const snzTokens = {
  font: {
    family: "system-ui, -apple-system, \"Segoe UI\", sans-serif",
    familyMono: "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace",
    sizeGround: "1rem",
    sizeSmall: "0.875rem",
    sizeTitle: "1.25rem",
    weightRegular: 400,
    weightSemibold: 600,
    weightBold: 700,
    lineHeightBody: 1.65,
    lineHeightHeading: 1.3,
  },
  space: {
    xs: "0.3rem",
    sm: "0.55rem",
    md: "0.9rem",
    lg: "1.4rem",
    rowY: "0.65rem",
  },
  size: {
    control: "2.4rem",
    targetMin: "24px",
  },
  radius: {
    sm: "6px",
    md: "10px",
  },
  border: {
    line: "1px",
    band: "3px",
    focus: "2px",
    focusOffset: "1px",
    disabledStyle: "dashed",
  },
  shadow: {
    raised: "0px 2px 8px 0px rgb(0 0 0 / 0.25)",
    modal: "0px 8px 24px 0px rgb(0 0 0 / 0.3)",
  },
  motion: {
    state: 140,
    spin: 700,
    spinReduced: 2000,
    toastMin: 1800,
    toastMax: 6000,
  },
  opacity: {
    disabled: 0.45,
    scrim: 0.7,
  },
  icon: {
    viewbox: 24,
    strokeWidth: 2,
    sizeSm: "16px",
    sizeMd: "20px",
  },
} as const;

export type SnzTokens = typeof snzTokens;

export interface SnzTheme {
  readonly family: SnzColorFamily;
  readonly mode: SnzColorMode;
  readonly color: SnzColors;
  readonly tokens: SnzTokens;
}

// Shaped for Emotion's ThemeProvider. Pass the mode after resolving OS-follow, not the user's choice.
export function snzTheme(family: SnzColorFamily, mode: SnzColorMode): SnzTheme {
  return { family, mode, color: snzColors[family][mode], tokens: snzTokens };
}
