// Generates internal/search/model.go from the exact tiny-segmenter npm model,
// so the Go port's scoring tables match the JS implementation byte-for-byte.
// Run from repo root:  node tools/segmenter-parity/gen_model.mjs
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const require = createRequire(import.meta.url);
const TinySegmenter = require("tiny-segmenter");
const seg = new TinySegmenter();

if (seg.BIAS__ !== -332) {
  throw new Error(`unexpected BIAS__ ${seg.BIAS__}; update segmenter.go const bias`);
}

// JS model field -> Go package-level var name.
const fields = [
  ["BC1__", "bc1"], ["BC2__", "bc2"], ["BC3__", "bc3"],
  ["BP1__", "bp1"], ["BP2__", "bp2"],
  ["BQ1__", "bq1"], ["BQ2__", "bq2"], ["BQ3__", "bq3"], ["BQ4__", "bq4"],
  ["BW1__", "bw1"], ["BW2__", "bw2"], ["BW3__", "bw3"],
  ["TC1__", "tc1"], ["TC2__", "tc2"], ["TC3__", "tc3"], ["TC4__", "tc4"],
  ["TQ1__", "tq1"], ["TQ2__", "tq2"], ["TQ3__", "tq3"], ["TQ4__", "tq4"],
  ["TW1__", "tw1"], ["TW2__", "tw2"], ["TW3__", "tw3"], ["TW4__", "tw4"],
  ["UC1__", "uc1"], ["UC2__", "uc2"], ["UC3__", "uc3"],
  ["UC4__", "uc4"], ["UC5__", "uc5"], ["UC6__", "uc6"],
  ["UP1__", "up1"], ["UP2__", "up2"], ["UP3__", "up3"],
  ["UQ1__", "uq1"], ["UQ2__", "uq2"], ["UQ3__", "uq3"],
  ["UW1__", "uw1"], ["UW2__", "uw2"], ["UW3__", "uw3"],
  ["UW4__", "uw4"], ["UW5__", "uw5"], ["UW6__", "uw6"],
];

const lines = [];
lines.push("// Code generated by tools/segmenter-parity/gen_model.mjs; DO NOT EDIT.");
lines.push("// Source: tiny-segmenter npm model (TinySegmenter 0.2, Taku Kudo).");
lines.push("");
lines.push("package search");
lines.push("");

for (const [jsField, goVar] of fields) {
  const obj = seg[jsField];
  if (!obj || typeof obj !== "object") {
    throw new Error(`missing model field ${jsField}`);
  }
  const entries = Object.entries(obj);
  lines.push(`var ${goVar} = map[string]int{`);
  for (const [key, value] of entries) {
    if (!Number.isInteger(value)) {
      throw new Error(`non-integer value for ${jsField}[${key}]: ${value}`);
    }
    // JSON.stringify yields a valid Go double-quoted string for these keys
    // (Japanese text, ASCII punctuation; no backslash/quote chars present).
    lines.push(`\t${JSON.stringify(key)}: ${value},`);
  }
  lines.push("}");
  lines.push("");
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const out = path.resolve(__dirname, "../../internal/search/model.go");
writeFileSync(out, lines.join("\n"), "utf8");
console.error(`wrote ${out} (${fields.length} tables)`);
